# Generated by Django 4.2.5 on 2024-01-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_category_event_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='free_tickets',
            field=models.BooleanField(default=True),
        ),
    ]
