# Generated by Django 4.2.5 on 2024-01-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('conferences', 'Conferences'), ('expos', 'Expos'), ('concerts', 'Concerts'), ('festivals', 'Festivals'), ('community', 'Community'), ('another', 'Another')], default='another', max_length=25),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
