# Generated by Django 4.2.5 on 2024-01-14 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_event_free_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organizer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_organize', to=settings.AUTH_USER_MODEL),
        ),
    ]
