# Generated by Django 4.2.5 on 2024-01-14 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='free_tickets',
            field=models.PositiveIntegerField(default=models.PositiveIntegerField(default=0)),
        ),
    ]
