# Generated by Django 4.2.5 on 2024-01-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_free_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='free_tickets',
            field=models.PositiveIntegerField(),
        ),
    ]
