# Generated by Django 4.2.5 on 2024-01-28 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_free_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='like',
        ),
        migrations.AddField(
            model_name='event',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
