# Generated by Django 5.0 on 2023-12-17 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_dark_mode', models.BooleanField(default=False)),
                ('is_show_notifications', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='settings',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.settings'),
        ),
    ]
